version: 2
updates:
  - package-ecosystem: "docker" # See documentation for possible values
    directory: "grafana" # Location of package manifests
    schedule:
      interval: "weekly"
      
   - package-ecosystem: "docker" # See documentation for possible values
    directory: "jenkins" # Location of package manifests
    schedule:
      interval: "weekly"

