version: 2
updates:
  - package-ecosystem: "docker"
    directory: "grafana"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "docker"
    directory: "jenkins"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
